##spring:
##  datasource:
##    generate-unique-name: false
##    name: taco

#jdbc:h2:mem:taco - url ??

spring:
  cassandra:
    keyspace-name: taco_cloud
    schema-action: recreate
    local-datacenter: datacenter1